version: '3.1'  # Use a suitable version

services:
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Replace with your username
      MONGO_INITDB_ROOT_PASSWORD: secret # Replace with your password
    volumes:
      - my-mongo-volume:/data/db

volumes:
  my-mongo-volume:
