version: "3.9"
services:
  drupal:
    image: drupal:7-apache
    ports:
      - "80:80"
    volumes:
      - ../libraries:/mnt/h5p/libraries
      - drupal-storage:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  db:
    image: mysql:5.7
    volumes:
      - db-storage:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
volumes:
  drupal-storage: {}
  db-storage: {}